### ISSUE TITLE
Choose and publish appropriate licence

### ISSUE THREAD

**Issue by michalporeba** [co-cddo/linked-data#1]
What is the best / the most appropriate licence for public documents published by the Civil Service organisations? 
Is there a suitable, widely accepted license? For the code we often use MIT, but it doesn't appear to be an obvious choice for non-code assets.

**Comment by ac0yne** [comment]
Crown copyright

**Comment by michalporeba** [comment]
Thanks @ac0yne for the suggestion. I have done some reading about it and the Crown copyright appears to be not open enough for truly public work. However, it led me to reading about [OGL](https://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/), specifically OGL-UK-3.0, which is compatible with [CC-BY](https://creativecommons.org/licenses/by/4.0/) license. It is also in line with [The Re-use of Public Sector Information Regulations 2015](https://www.legislation.gov.uk/uksi/2015/1415/contents/made). 

Thanks for pointing me in the right direction.
